WeaponsList["Midnight Blade"] = {
name : "Midnight Blade",
source : ["HB", 1],
regExpSearch : /Midnight Blade/i,
type: "Martial",
ability : 2,
abilitytodamage : true,
damage : [1, 8, "slashing"],
range : "Melee",
description : "Finesse, light",
tooltip : "I have a +3 on attack rolls for this Magic Weapon. On a Nat 20 Roll, my slash cuts through anything, halving enemy HP. I can choose to use the slash",
list : "melee",
modifiers : [0, "Prof"],
isMagicWeapon : true,
}
